#!/bin/sh

# startup programs
sxhkd &
compton -b
pulseaudio --start -D
~/.fehbg
bar &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width	5
bspc config window_gap		12

bspc config split_ratio		0.60
bspc config borderless_monocle	true
bspc config gapless_monocle	true


bspc rule -a Surf state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Pavucontrol state=floating
bspc rule -a Lxappearance state=floating

# Source wal color scheme
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
